environment = "prod"
snowflake_account_name = ""
snowflake_organization_name = ""
snowflake_username = "TERRAFORM_DEV_SVC"
snowflake_account_role = "ACCOUNTADMIN"
snowflake_account_authenticator = "SNOWFLAKE_JWT"
private_key_path = "/home/runner/.ssh/prod_snowflake_tf_snow_key.p8"
