# .github/workflows/terra.yml
name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/prod_snowflake_tf_snow_key.p8
          chmod 600 ~/.ssh/prod_snowflake_tf_snow_key.p8

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Plan
        run: terraform plan -var-file=${{ vars.ENV }}.tfvars -out=tfplan.binary

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/prod_snowflake_tf_snow_key.p8
          chmod 600 ~/.ssh/prod_snowflake_tf_snow_key.p8

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ vars.ENV }}.tfvars tfplan.binary
